version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo "Entered the pre-build phase"
      - $(aws ecr get-login  --no-include-email --region $AWS_REGION)
  build:
    commands:
      - echo "Entered build phase"
      - cd Authentication
      - mvn compile
      - mvn package
      - echo " building docker image"
      - docker build -t service/authapp .
      - docker tag service/authapp 430321133782.dkr.ecr.eu-west-2.amazonaws.com/j008-truyum1-auth-repo:authapp
  post_build:
    commands:
    - echo "Entered the post-build phase"
    - docker push 430321133782.dkr.ecr.eu-west-2.amazonaws.com/j008-truyum1-auth-repo:authapp
    - printf '[{"name":"authapp-container","imageUri":"%s"}]' 430321133782.dkr.ecr.eu-west-2.amazonaws.com/j008-truyum1-auth-repo:authapp > taskdefinition.json
artifacts:
  files:
    - Authentication/taskdefinition.json
    